version: "3.8"
services:
  app:
    build: .
    container_name: express-app
    ports:
      - "27017:27017"
      - "6379:6379"
    volumes:
      - .:/usr/src/app
      - /usr/src/app/node_modules
    depends_on:
      - mongo
      - redis
    environment:
      - MONGO_URI=mongodb://mongo:27017/dailycollege
      - REDIS_HOST=redis
      - REDIS_PORT=6379
    command: npm start
    networks:
      - app-network

  mongo:
    image: mongo:6
    container_name: mongo-db
    ports:
      - "27017:27017"
    volumes:
      - mongo-data:/data/db

  redis:
    image: redis:7
    container_name: redis-db
    ports:
      - "6379:6379"

volumes:
  mongo-data:
