version: "3.8"

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile.prod
    image: express-app:latest
    container_name: express-app
    ports:
      - "3000:3000"
    volumes:
      - .:/usr/src/app
      - node_modules:/usr/src/app/node_modules
    depends_on:
      - mongo
      - redis
    environment:
      - MONGO_URI=mongodb://mongo:27017/dailycollege
      - REDIS_HOST=redis
      - REDIS_PORT=6379
      - VIRTUAL_HOST=api.example.com
      - LETSENCRYPT_HOST=api.example.com
      - LETSENCRYPT_EMAIL=youremail@example.com
    command: npm start
    networks:
      - proxy-tier
      - app-network

  mongo:
    image: mongo:6
    container_name: mongo-db
    ports:
      - "27017:27017"
    volumes:
      - mongo-data:/data/db
    networks:
      - app-network

  redis:
    image: redis:7
    container_name: redis-db
    ports:
      - "6379:6379"
    networks:
      - app-network

  nginx:
    image: nginx:alpine
    container_name: nginx
    restart: always
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./nginx/conf.d:/etc/nginx/conf.d
      - /etc/letsencrypt:/etc/letsencrypt
    depends_on:
      - app
    networks:
      - app-network

volumes:
  mongo-data:
  node_modules:

networks:
  app-network:
    driver: bridge
